locales:
  en:
    name: Guarani Keyboards
    description: Mobile OS keyboards for the Guarani language from the Divvun group at UiT.
  nb:
    name: Guarani tastatur
    description: Mobiltastatur for Guarani fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
