template = "https://github.com/giellalt/template-keyboard-und"
rev_id = 19
template_sha = "a01af0ad71b8138c7ccbf8ccd049bf72463c30ea"

[replacements]
__UND2C__ = "gn"
__UNDEFINED__ = "Guarani"
__UND__ = "grn"
